handle all response in front dom
FACG6/enhance-a-smile pull request #118
Opened 2019-03-21 20:41 UTC by aminalakhsham

Relates #62 
Relates #40

2019-03-22 16:46 UTC, Jamalat-shamallakh approved these changes

2019-03-23 17:33 UTC, InassTubail requested changes
textContent is better than innerHTML and innerText as @jamalat say
Read this : 
https://blog.cloudboost.io/why-textcontent-is-better-than-innerhtml-and-innertext-9f8073eb9061

2019-03-23 17:39 UTC, aminalakhsham commented
> textContent

Done :)

2019-03-23 17:39 UTC, InassTubail approved these changes

2019-03-23 17:47 UTC, InassTubail approved these changes

2019-03-23 17:53 UTC, merged