add the Admin donate page
FACG6/enhance-a-smile pull request #135
Opened 2019-03-25 09:40 UTC by AbdallahAmmar96

add all relative files to admin donate page

2019-03-25 22:47 UTC, InassTubail requested changes
Remove comments from /controllers/admin/donate/donate.js

2019-03-26 10:08 UTC, Jamalat-shamallakh requested changes

2019-03-26 10:08 UTC, Jamalat-shamallakh commented on src/controllers/admin/donate/donate.js
> +// const update = require('');
delete comments

2019-03-26 13:28 UTC, tomduggan85 commented on src/views/admin/donates.hbs
> +  {{#unless card.state}}
@AbdallahAmmar96 You might need `this.state` to access the state of the current card in the `#each` loop

2019-03-26 13:30 UTC, tomduggan85 commented on src/views/admin/donates.hbs
> +        <h4 class="city">City: {{cityName}}</h4>
@AbdallahAmmar96 Are fullName, phoneNumber, email and cityName attributes of the current card in the `#each` loop?  I think then you'd need to use `this.fullName`, `this.phoneNumber`, and so on.
Or it looks like handlebars 3.0 has a feature called block parameters which makes it easier to write `#each` loops, if you're interested:  https://handlebarsjs.com/block_helpers.html#block-params

2019-03-26 13:30 UTC, tomduggan85 commented on src/views/admin/donates.hbs
> +        <h4 class="season">Season(s): {{season}}</h4>
@AbdallahAmmar96 Similar to my above comment, you might need `this.numberOfPieces`, `this.quality`, and so on.

2019-03-26 16:31 UTC, closed without merging